name: catalog
description: Take pictures of things and catalog them.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  camera: ^0.10.3+1
  flutter_gen: ^5.2.0
  image_picker: ^0.8.7
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  assets:
    - img/

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "img/logo.png"
