= esLister

Take pictures of things and catalog them.
Allows multiple pix per item, a brief description,
and an estimated valuation.

Useful for estate sales, yard sales/downsizing, etc.
Hence the name: esLister can stand for:

* Estate Sale Lister
* Extra Stuff Lister
* Ex's Stuff Lister

There will someday be plugins to allow uploading the
lists to various auction sites.

== N.B. Re Git Clone

The program name is "esLister", but Flutter requires
a lower-case directory name.
Github doesn't care, so please, when cloning this repo,
clone it as "eslister" not as "esLister".

== Logo

The tawdry logo is from a sketch I did for an earlier
(and now dead) program called jrLister,
which was a desktop app with similar scope.
If you don't like the logo, make me a better one :-)

== TODO

Main list: + GestureDetector, long-press menu with edit, delete

Edit page to populate, d'oh!

Loading and Saving of images in DB (own table)

Export (in JSON only, until upload plugins magically appear).

Settings: add/remove default locations; presets for home,office

Add a "project name" settings, switch between projects (tabs?).

Tweak "Add image" box / border(s) UI in ItemPage.
