= esLister

Take pictures of things and catalog them.
Allows multiple pix per item, a brief description,
and an estimated valuation.

Useful for estate sales, yard sales/downsizing, etc.
Hence the name: esLister can stand for:

* Estate Sale Lister
* Extra Stuff Lister
* Ex's Stuff Lister (only if they walked out on you and left stuff behind!)

There should someday be plugins to allow uploading the
lists to various auction sites.

== N.B. Re Git Clone

The program name is "esLister", but Flutter requires
a lower-case directory name.
Github doesn't care, so please, when cloning this repo,
clone it as "eslister" not as "esLister".

== Logo

The terrible logo - of a person happy because they're de-cluttering -
is from a sketch I did for an earlier
(and now dead) program called jrLister,
which was a desktop app with similar scope.
It's meant to represent "taking a look around",
which is what you're doing when using this app.
If you can make a better logo, do it, and send a pull request.

== TODO

The ToDo list for this project has moved to
https://github.com/IanDarwin/esLister/issues/[our github page].

If you are allergic to github for some reason, you can send
suggestions or old-style patches via email; start at
https://darwinsys.com/contact[my contact-me page].

