= esLister

Take pictures of things and catalog them.
Allows multiple pix per item, a brief description,
and an estimated valuation.

Useful for estate sales, yard sales/downsizing, etc.
Hence the name: esLister can stand for:

* Estate Sale Lister
* Extra Stuff Lister
* Ex's Stuff Lister

There will someday be plugins to allow uploading the
lists to various auction sites.

== N.B. Re Git Clone

The program name is "esLister", but Flutter requires
a lower-case directory name.
Github doesn't care, so please, when cloning this repo,
clone it as "eslister" not as "esLister".

== Logo

The terrible logo is from a sketch I did for an earlier
(and now dead) program called jrLister,
which was a desktop app with similar scope.
It's meant to represent "taking a look around".
If you can make a better logo, do it, and send a pull request.

== TODO

Export (in JSON only, until upload plugins magically appear).

Nav bar needs some love.

Settings needs love too:
	add/remove default locations; presets for home,office

Add a "project name" settings, switch between projects (tabs?).
	e.g., "Smith Estate" vs "Sidhartha Estate", or
	"Cheap Leftover stuff" vs "Expensive Estate Stuff"

